#!/bin/sh
# wayland stuff
export QT_QPA_PLATFORM=wayland
export ELM_DISPLAY=wl
export GDK_BACKEND=wayland
export SDL_VIDEODRIVER=wayland,x11
export WLR_NO_HARDWARE_CURSORS=1
export _JAVA_AWT_WM_NONREPARENTING=1
export MOZ_ENABLE_WAYLAND=1
export PROTON_ENABLE_WAYLAND=1

export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=sway
export ELECTRON_OZONE_PLATFORM_HINT=wayland
exec dbus-run-session sway --unsupported-gpu
