# Yazi theme file
[app]

[indicator]
padding = { open = "█", close = "█"}

[tabs]
active = { bg = "blue", fg = "black"}
inactive = { bg = "black", fg = "blue"}
sep_inner = { open = "█", close = "█"} 
sep_outer = { open = "█", close = "█"} 

[mode]
normal_main = {bg = "black", fg = "cyan"}
normal_alt = {bg = "darkgray", fg = "cyan"}
select_main = {bg = "black", fg = "red"}
select_alt = {bg = "darkgray", fg = "red"}

[status]
sep_left = { open = "█", close = "█"}
sep_right = { open = "█", close = "█"}
