#exec-once=$HOME/Scripts/random-wallpaper.sh
exec-once=wbg $HOME/Pictures/wallpapers/nix_01.png
exec-once=waybar -c /home/pakin/.config/mango/waybar/config.jsonc -s /home/pakin/.config/mango/waybar/style.css
exec-once=mpc stop
exec-once=fcitx5
#exec-once=$HOME/Scripts/runit-user-service.sh
