#exec-once=$HOME/Scripts/random-wallpaper.sh
exec-once=wbg $HOME/Pictures/wallpapers/nix_01.png
exec-once=waybar -c /home/pakin/.config/mango/waybar/config.jsonc -s /home/pakin/.config/mango/waybar/style.css
exec-once=$HOME/.config/mango/scripts/display_and_mouse.sh
exec-once=brightnessctl set 40%
exec-once=$HOME/Scripts/low_battery.sh
