# More option see https://github.com/DreamMaoMao/mango/wiki/
source=./autostart.conf
source=./keybinds.conf
source=./layouts.conf
source=./themes.conf
source=./rules.conf
source=./inputs.conf

# environment
env=QT_QPA_PLATFORM,wayland;xcb
env=ELM_DISPLAY,wl
env=GDK_BACKEND,wayland
env=SDL_VIDEODRIVER,wayland,x11
env=WLR_NO_HARDWARE_CURSORS,1
env=_JAVA_AWT_WM_NONREPARENTING,1
env=MOZ_ENABLE_WAYLAND,1
env=PROTON_ENABLE_WAYLAND,1
env=ELECTRON_OZONE_PLATFORM_HINT,wayland
env=INIT_UNIX_BACKEND,x11

animations=1
animation_type_open=zoom
animation_type_close=zoom

# Misc
no_border_when_single=0
axis_bind_apply_timeout=100
focus_on_activate=1
idleinhibit_ignore_visible=0
sloppyfocus=1
warpcursor=1
focus_cross_monitor=0
focus_cross_tag=0
enable_floating_snap=0
snap_distance=30
cursor_size=24
drag_tile_to_tile=1
drag_tile_small=1

# Trackpad
# need relogin to make it apply
disable_trackpad=0
tap_to_click=1
tap_and_drag=1
drag_lock=1
trackpad_natural_scrolling=0
disable_while_typing=1
left_handed=0
middle_button_emulation=0
swipe_min_threshold=1

# mouse
# need relogin to make it apply
mouse_natural_scrolling=0
mouse_accel_profile=1

# Mouse Button Bindings
# btn_left and btn_right can't bind none mod key
mousebind=SUPER,btn_left,moveresize,curmove
#mousebind=NONE,btn_middle,togglemaximizescreen,0
mousebind=SUPER,btn_right,moveresize,curresize

# Axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client

# layer rule
#layerrule=animation_type_open:zoom,layer_name:rofi
#layerrule=animation_type_close:zoom,layer_name:rofi
