windowrule=tags:7,appid:rmpc
windowrule=tags:7,appid:Spotify
windowrule=tags:8,appid:vesktop
windowrule=tags:9,appid:thunderbird

windowrule=isfloating:1,title:wiremix,appid:wiremix
windowrule=isfloating:1,title:bluetui,appid:bluetui
