windowrule=tags:7,appid:rmpc
windowrule=tags:7,appid:Spotify
windowrule=tags:8,appid:vesktop
windowrule=tags:9,appid:thunderbird

windowrule=title:wiremix,isfloating:1,width:0.8,height:0.8
windowrule=title:bluetui,isfloating:1,width:0.8,height:0.8
windowrule=title:impala,isfloating:1,width:0.8,height:0.8
