borderpx=2
gappih=4
gappiv=4
gappoh=8
gappov=8

# Appearance
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
rootcolor=0x2c2e33ff
bordercolor=0x4f525800 # no border when not focus
dropcolor=0xb3f6c055
splitcolor=0xfce094ff
focuscolor=0xa6dbffff
maximizescreencolor=0xb3f6c0ff
urgentcolor=0xffc0b9ff
scratchpadcolor=0x4f5258ff
globalcolor=0xffcaffff
overlaycolor=0x8cf8f7ff
