#!/bin/sh
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=wlroots
export XDG_CURRENT_DESKTOP=wlroots

export _JAVA_AWT_WM_NONREPARENTING=1
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland

# Set NVIDIA-specific environment variables
export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia

slstatus -s  | dwl -s "sh -c $HOME/Scripts/dwl-startup.sh" > "$HOME/dwl.log" 2>&1
