# -*- conf[main]
[main]
include=/usr/share/foot/themes/nvim-dark
shell=/usr/bin/zsh
term=foot
locked-title=no
font=JetBrainsMonoNerdFontPropo:size=13,monospace:size=13
line-height=20
letter-spacing=0.2
pad=20x10
[environment]
[security]
osc52=enabled
[bell]
[desktop-notifications]
[scrollback]
[url]
[cursor]
style=block
blink=no
[mouse]
[touch]
[colors-dark]
alpha=0.85
#background=07080d
#bright0=9b9ea4
#foreground=ebeef5
#cursor=07080d e0e2ea
[csd]
[key-bindings]
[search-bindings]
[url-bindings]
[text-bindings]
[mouse-bindings]
