[opener]
play = [
	{ run = "mpv %s", orphan = true, for = "unix" },
]
edit = [
	{ run = "$EDITOR %s", block = true, for = "unix" },
]
open = [
	{ run = "xdg-open %s", desc = "Open" },
]

[open]
prepend_rules = [
    { name = "*.pdf", use = "open"},
    { name = "*.epub", use = "open" },
    { name = "*.jpeg", use = "open"},
    { name = "*.jpg", use = "open"},
    { name = "*.png", use = "open"},
]
