playback_state = "Playing"
backend = "pulseaudio"
use_nerdfont = true
notify = true
default_keybindings = true
shuffle = true
library_tabs = [ "playlists", "albums", "artists", "podcasts", "browse" ]
[theme]
background = "#07080D"
primary = "#E0E2EA"
secondary = "#c4c6cd"
title = "#8cf8f7"
playing = "#b3f6c0"
playing_selected = "#b3f6c0"
playing_bg = "#14161b"
highlight = "#a6dbff"
highlight_bg = "#07080D"
error = "#ffc0b9"
error_bg = "#5e0009"
statusbar = "#8cf8f7"
statusbar_progress = "#b3f6c0"
statusbar_bg = "#07080d"
cmdline = "#b3f6c0"
cmdline_bg = "#2c2e33"
