#!/bin/sh

. "$HOME/Scripts/wmenu-cmd"

choice=$(printf "Select Area\nFull Screen" | wmenu_cmd -p 'Mode')
[ -z "$choice" ] && exit 1  

case $choice in
  "Select Area") 
    use_slurp=true 
    slurp=$(slurp) 
    [ -z "$slurp" ] && exit 1
    ;;
  "Full Screen") use_slurp=false ;;
  *) exit 1;
esac

choice=$(printf "Clipboard\nFile" | wmenu_cmd -p 'Save to')

case $use_slurp in
  "true") 
    case $choice in
      "Clipboard") grim -g "$slurp" - | wl-copy ;;
      "File") 
        filename=$(printf '' | wmenu_cmd -p "Enter file name") 
        if [ -n "$filename" ]; then
          grim -g "$slurp" "$HOME/Pictures/screenshots/$filename" 
        fi ;;
      *) exit 1 ;;
    esac ;;

  "false")
    case $choice in
      "Clipboard") grim - | wl-copy ;;
      "File") 
        filename=$(printf '' | wmenu_cmd -p "Enter file name") 
        if [ -n "$filename" ]; then
          grim  "$HOME/Pictures/screenshots/$filename"
        fi ;;
      *) exit 1 ;;
    esac ;;
esac
