# keyboard
repeat_rate=35
repeat_delay=200
numlockon=0
xkb_rules_layout=us,th
xkb_rules_variant=qwerty,
#bind=SUPER,space,switch_keyboard_layout
xkb_rules_options=grp:win_space_toggle
#xkb_rules_options=grp:win_space_toggle,custom:hjkl

# devices rules
devicerule=name:AT Translated Set 2 keyboard,kb_layout:us,kb_variant:colemak_dh
devicerule=name:kanata,kb_layout:us,kb_variant:colemak_dh
devicerule=name:ZSA Technology Labs Voyager,kb_layout:us,kb_variant:colemak_dh_ortho
